// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Address: typeof import('./components/Address.vue')['default']
    CarbonChevronLeft: typeof import('~icons/carbon/chevron-left')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ImprintText: typeof import('./components/ImprintText.vue')['default']
    Left: typeof import('./components/Left.vue')['default']
    Order: typeof import('./components/Order.vue')['default']
    README: typeof import('./components/README.md')['default']
    SkeletonIndex: typeof import('./components/SkeletonIndex.vue')['default']
    Zines: typeof import('./components/Zines.vue')['default']
    ZoomArea: typeof import('./components/ZoomArea.vue')['default']
  }
}

export { }
